### PR TITLE
allow the use of dynamic ids

### PR DESCRIPTION
**Pull request by flc**
This allows the id attr to be dynamic.
related issue: #385

### CODE REVIEW

**Comment by allenhwkim** [comment]
This has been fixed as a different way by compiling properly ids.

**Comment by flc** [comment]
However the example (testapp/maps_with_dynamic_ids.html) I've included in the pull request still doesn't work. But it still does with that one line fix.

**Comment by allenhwkim** [comment]
The following example will do the job you want to do
```
<!doctype html>
<html ng-app="myapp">
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script src="script-tags-for-development.js"></script>
<script>
  var app = angular.module('myapp', ['ngMap']);
  app.controller('MyCtrl', function(NgMap) {
    var vm = this;
    vm.objects = [
      {'id': 0, 'positions': [ [-14,132], [-15,131], [-16,130] ]},
      {'id': 1, 'positions': [ [-24,132], [-25,131], [-26,130] ]},
      {'id': 2, 'positions': [ [-29,132], [-30,131], [-31,130] ]}
    ];
  });
</script>
</head>
<body ng-controller="MyCtrl as vm">
  <div style="width:30%;display:inline-block;margin:5px;" ng-repeat="obj in vm.objects">
    <ng-map id="{{'map'+ obj.id}}" center="{{obj.positions[1]}}" zoom-to-include-markers="true">
      <marker ng-repeat="pos in obj.positions" position="{{pos}}"></marker>
    </ng-map>
    <br/> 
  </div>
</html>
```

**Comment by flc** [comment]
Thanks for your help, Allen! My main problem was that I couldn't get the map object with `NgMap.getMap` if the id was defined this way: `id="map-{{ obj.id }}"`. But it looks like it works if I define it the way you do it in your example: `id="{{'map-'+ obj.id}}"`. It's a bit weird though.

I need to get the map and do the fitting/centering manually because I don't necessarily only have markers so the `zoom-to-include-markers="true"` doesn't really help, I have multiple polylines or polygons AND also markers occasionally and the map should fit to all of those. Anyway, thank you!

**Comment by allenhwkim** [comment]
Yes, it's weird because the attribute is evaluated against scope only if it starts with `{`. I should have found better way, e.g., compile all attributes if any `{` is found, but it's good for now. Thanks for your contribution @flc

**Pull request closed without merging**
