### PR TITLE
Added a new option (geo-location-options)

### PR DESCRIPTION
**Pull request by sebrojas14**
I have a problem; i don't know hoe to make the new parameter can receive an Object (now is received as a strin representation)

Description: The navigator geolocations options. i.e. { maximumAge: 3000, timeout:
5000, enableHighAccuracy: true }. If none specified, { timeout: 5000 }.
If timeout not specified, timeout: 5000 added

### CODE REVIEW

**Comment by sebrojas14** [comment]
What do you think of change it and enable to receive the geoLocationOptions as an object, an scope variable and not only a object json representation?

**Comment by sebrojas14** [comment]
Any plans when this is gonna be released?

**Comment by allenhwkim** [comment]
not released yet?

**Comment by sebrojas14** [comment]
The last release was 25 ago...and you merged the pull request 23 days ago..so I supused that no

**Pull request merged**
