### PR TITLE
New feature: Info window external template

### PR DESCRIPTION
**Pull request by harm-less**
This feature will allow you to have the content from the info window loaded from an external template using the ```$templateCache```.

I needed this method because I wrapped ```ng-map``` inside my own directive that serves as a reusable component. Dynamic template content turned out to be hard and this was the only way I could make this work as far as I know.

A demo can be viewed from file ```infowindow-template.html```.

### CODE REVIEW

**Comment by allenhwkim** [comment]
@harm-less thanks, I will look into it later. In case I forgot, ping me again.

**Comment by harm-less** [comment]
Alright, will do. It's probably for the best because I thought of something that wasn't yet included in this pull request. So I'll first finish that. Hopefully that will be before I leave the office, otherwise I won't be able to update it before Thursday...

**Comment by harm-less** [comment]
Well, I did it, I made sure a promise was added so the template could also be downloaded first if that's necessary.

Let me know what you think.

**Comment by harm-less** [comment]
Hey allen, did you already had time to take a look at the request?

**Comment by harm-less** [comment]
Thanks Allen!
Do you already know when a new release will be created?

**Comment by allenhwkim** [comment]
I will add a new release soon with angular-jsodoc improvement

**Comment by chiptus** [comment]
+1

**Pull request merged**
