### PR TITLE
Update zoom when markers are added

### PR DESCRIPTION
**Pull request by xavierjohn**
When markers are added, the zoom is automatically adjusted.

### CODE REVIEW

**Comment by allenhwkim** [comment]
tried the same thing with no success in directives/map.js. Don't know why

        if (attrs.zoomToIncludeMarkers == 'auto') {
          scope.$watch(function() {
            return scope.map.markers;
          }, function(n, o) {
            console.log('bbbbbbbbbbbbbbbbbb', scope.map, ctrl.map);
            ctrl.zoomToIncludeMarkers();
          });
        }

**Comment by allenhwkim** [comment]
Added this feature by emitting an event and consuming it. The example is [here](https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_zoom_to_include_markers.html)

**Comment by xavierjohn** [comment]
Cool, thanks.

**Comment by xavierjohn** [comment]
You may want to update your documentations about zoom-to-include-markers='true' and zoom-to-include-markers='auto'

**Pull request closed without merging**
