### PR TITLE
Added RichMarker

### PR DESCRIPTION
**Pull request by aaronbroad**
Forgive me if I'm not following protocol in some way as this is all new to me. Any guidance would be appreciated!

This PR shows the change I have in mind to add the ability to use the Google Maps JS util library RichMarker found [here](http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/). RichMarker allows any HTML/DOM elements to be used as markers.

The RichMarker library must be included separately. If the RM lib is included, the *marker* directive will use RichMarker methods and events (instead of the default Google Maps JS marker).

Please advise as to next steps here. Many thanks.

### CODE REVIEW

**Comment by allenhwkim** [comment]
I have to refuse this pull request because I believe that RichMarker must be a separate directive from Marker directive.
The approach suggested is that user uses 'marker' directive, then internally It decides to use `marker` or `rich marker` based on environment. This approach works for small and private project, but not big and open project like this.

**Comment by aaronbroad** [comment]
I understand. I started to make it its own directive but realized that it would effectively require duplicating so much of the marker directive. Didn't seem too DRY to me.

Perhaps there's a more elegant solution, say by adding a "rich-marker' attribute to the marker directive, to be used something like this:
<marker rich-marker="true" .../>

**Comment by allenhwkim** [comment]
The reason for making a separate directive is very simple.

1. RickMarker is not a Google supported code. So when it goes wrong, it does not affect the other code.
    Thus, I want it to have a separate code.

2. As you see in this example, view-source:https://googlemaps.github.io/js-rich-marker/examples/richmarker.html?, Rich marker uses 'content' as you see in line 75, which is different from Marker. We cannot pass that content as an attribute.

It must be angular compiled with scope respected. I see this has some similarity to InfoWindow.

3. As you see in their source code, view-source:https://googlemaps.github.io/js-rich-marker/src/richmarker.js, RichMarker does not use Marker for their base, but OverlayView class, which has very different attributes and events than Marker.

There are reasons that why ngMap does not support 3rd party or community codes, and the biggest one is that sometimes it does not works as Google maps design.

If ngMap module accept RichMarker as a directive, it will be the community code, which won't be maintained by the core developer by keeping it as a separate module. e.g., angular-resource.js, ng-map.rick-marker.js.

**Comment by aaronbroad** [comment]
Makes sense. Thanks for your thoughtful response!

**Pull request closed without merging**
