### PR TITLE
[map-lazy-load] use `onload` instead of callback.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by allenhwkim** [comment]
callback is only called when map api is fully initialized and I think it is different from element onload. What do you think about it?

**Comment by aitboudad** [comment]
The only benefit here is the loading time which is faster than the current way,
waiting to the map is fully initialized is useless here as the injected script will never be executed before the map is loaded.

**Comment by allenhwkim** [comment]
Is there a chance that we see the error of `google is undefined' ?

**Comment by aitboudad** [comment]
`google is undefined' won't happen, but google suggest the callback way so I'm going to close this PR right now!

**Comment by allenhwkim** [comment]
sorry for @aitboudad. I really appreciate you looking into this matter.

**Pull request closed without merging**
